// [WAJIB GANTI]: Masukkan URL Web App GAS Anda di bawah ini
const GAS_URL = 'https://script.google.com/macros/s/AKfycbxBFrvw8Psn4P-KZzb8Shrxrscn6qNlujWowHVX4oPSUM2r1YxE5awEbLMIFiDhAtA5/exec';

// Keamanan: Mencegah injeksi XSS (Cross-Site Scripting)
const escapeHTML = (str) => {
  return String(str).replace(/[&<>'"]/g, 
    tag => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[tag])
  );
};

// Modul User Interface (Notif, Loading, Terminal)
const ui = {
  loading: (id, text) => {
    const btn = document.getElementById(id);
    btn.dataset.original = btn.innerText;
    btn.innerText = text;
    btn.disabled = true;
  },
  reset: (id) => {
    const btn = document.getElementById(id);
    btn.innerText = btn.dataset.original;
    btn.disabled = false;
  },
  toast: (msg, type = 'success') => {
    const toast = document.getElementById('toast');
    toast.className = `toast ${type}`;
    toast.innerHTML = escapeHTML(msg);
    toast.classList.remove('hidden');
    setTimeout(() => toast.classList.add('hidden'), 3500);
  },
  log: (msg, type = 'info') => {
    const term = document.getElementById('terminal-log');
    const color = type === 'error' ? '#ef4444' : '#22c55e';
    const timestamp = new Date().toLocaleTimeString('id-ID');
    term.innerHTML += `<br><span style="color: #64748b">[${timestamp}]</span> <span style="color: ${color}">> ${escapeHTML(msg)}</span>`;
    term.scrollTop = term.scrollHeight; // Auto-scroll ke bawah
  }
};

// Modul Utama Alur Kerja
const app = {
  email: '',
  
  activate: async () => {
    const emailInput = document.getElementById('input-email').value.trim();
    if (!emailInput) return ui.toast('Email tidak boleh kosong', 'error');

    ui.loading('btn-auth', 'Memproses...');
    try {
      const response = await fetch(GAS_URL, {
        method: 'POST',
        body: JSON.stringify({ action: 'activateAccount', email: emailInput })
      });
      const res = await response.json();
      
      if (res.status === 'success') {
        app.email = emailInput;
        document.getElementById('panel-auth').classList.add('hidden');
        document.getElementById('panel-config').classList.remove('hidden');
        document.getElementById('panel-ai').classList.remove('hidden');
        
        const badge = document.getElementById('user-badge');
        badge.innerText = 'Online';
        badge.classList.add('active');
        
        ui.toast(res.data.message);
        ui.log('Autentikasi berhasil. Workspace siap.');
      } else {
        throw new Error(res.message);
      }
    } catch (err) {
      ui.toast('Gagal terhubung ke server', 'error');
      ui.log(`Koneksi ditolak: ${err.message}`, 'error');
    } finally {
      ui.reset('btn-auth');
    }
  },

  save: async () => {
    const id = document.getElementById('input-project').value.trim();
    const code = document.getElementById('input-code').value;
    
    if (!id || !code) return ui.toast('Project ID dan Kode harus diisi', 'error');

    ui.loading('btn-save', 'Menyimpan...');
    ui.log('Mengompilasi data ke Cloud Serverless...');
    
    try {
      const response = await fetch(GAS_URL, {
        method: 'POST',
        body: JSON.stringify({ action: 'saveProject', projectId: id, email: app.email, code: code })
      });
      const res = await response.json();
      
      if (res.status === 'success') {
        ui.toast('Berhasil disimpan');
        ui.log(`Project [${id}] tersimpan di Cloud.`);
      } else {
        throw new Error(res.message);
      }
    } catch (err) {
      ui.toast('Gagal menyimpan project', 'error');
      ui.log(`Gagal menyimpan: ${err.message}`, 'error');
    } finally {
      ui.reset('btn-save');
    }
  },

  publish: () => {
    const id = document.getElementById('input-project').value.trim();
    if (!id) return ui.toast('Silakan simpan project terlebih dahulu', 'error');
    
    const publicUrl = `${GAS_URL}?id=${id}`;
    ui.log(`Menyiapkan server publik...`);
    ui.log(`Membuka target: ${publicUrl}`);
    ui.toast('Menjalankan Web Browser...', 'success');
    window.open(publicUrl, '_blank');
  },

  askGemini: async () => {
    const promptInput = document.getElementById('input-prompt').value.trim();
    if (!promptInput) return ui.toast('Masukkan instruksi untuk AI.', 'error');
    
    ui.loading('btn-ai', 'AI Berpikir...');
    ui.log('Mengirim instruksi ke Gemini AI...', 'info');
    
    try {
      const response = await fetch(GAS_URL, {
        method: 'POST',
        body: JSON.stringify({ action: 'askGemini', prompt: promptInput })
      });
      const res = await response.json();
      
      if (res.status === 'success') {
        const codeEditor = document.getElementById('input-code');
        // Inject hasil ke editor (aman karena tidak langsung render DOM)
        codeEditor.value += `\n\n<!-- Generated by Gemini AI -->\n${res.data.answer}`;
        ui.toast('Kode berhasil di-generate!', 'success');
        ui.log('AI selesai. Kode telah ditambahkan ke editor.', 'success');
        document.getElementById('input-prompt').value = '';
      } else {
        throw new Error(res.message);
      }
    } catch (err) {
      ui.toast('Gagal menghubungi AI', 'error');
      ui.log(`AI Error: ${err.message}`, 'error');
    } finally {
      ui.reset('btn-ai');
    }
  }
};
